name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ["16"]

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm -v
          pnpm config set enable-pre-post-scripts true
          pnpm i --frozen-lockfile
        env:
          CI: true

      - name: Test
        run: pnpm t
        env:
          CI: true
